use LOCAL_DB;

-- drop TABLE if exists CHAT;
CREATE TABLE CHAT(
	CHAT_ID int unsigned zerofill auto_increment PRIMARY KEY,
    CHAT_PUBLICACION int unsigned,
	foreign key(CHAT_PUBLICACION) REFERENCES PUBLICACION(PUBLI_ID),

    CHAT_ULTIMO_MENSAJE datetime NOT NULL,
    CHAT_VISIBILIDAD bool NOT NULL
);

-- drop TABLE if exists INTERACCION;
CREATE TABLE INTERACCION(
	INT_CHAT int unsigned,
	foreign key(INT_CHAT) REFERENCES CHAT(CHAT_ID),
    
    INT_USUARIO int unsigned NOT NULL,
	foreign key(INT_USUARIO) REFERENCES USUARIO(USU_ID),

	primary key(INT_CHAT, INT_USUARIO),

    INT_VISIBLE bool NOT NULL
);
ALTER TABLE interaccion ADD COLUMN INT_NOTIFICACION bool DEFAULT 0;