use LOCAL_DB;

DROP EVENT IF EXISTS CONTADOR_DIAS;

DELIMITER $$
CREATE EVENT CONTADOR_DIAS ON SCHEDULE EVERY 1 day
	STARTS '2014-01-18 00:00:00' DO BEGIN
		UPDATE PUBLICACION SET PUBLI_TIEMPO = PUBLI_TIEMPO - 1 WHERE PUBLI_TIEMPO > 0;
		UPDATE PUBLICACION SET PUBLI_VISIBLE = 0 WHERE PUBLI_TIEMPO < 1;
	END
$$
	