use LOCAL_DB;

-- drop TABLE if exists CATEGORIA;
CREATE TABLE CATEGORIA(
	CAT_ID varchar(11) PRIMARY KEY,
    CAT_NOMBRE varchar(30) NOT NULL,
    CAT_SUPERIOR varchar(30) NOT NULL
);

-- drop TABLE if exists PUBLICACION;
CREATE TABLE PUBLICACION(
	PUBLI_ID varchar(15) PRIMARY KEY,
    PUBLI_AUTOR varchar(11) NOT NULL,
	foreign key(PUBLI_AUTOR) REFERENCES USUARIO(USU_ID),
    
    PUBLI_FECHA date NOT NULL,
    PUBLI_TITULO varchar(40) NOT NULL,
    PUBLI_DESCRIPCION varchar(100) NOT NULL,
    PUBLI_TIEMPO varchar(20) NOT NULL,
    PUBLI_FOTO varchar(200) NOT NULL,
    PUBLI_PRECIO varchar(20) NOT NULL,
    PUBLI_CATEGORIA varchar(11) NOT NULL,
	foreign key(PUBLI_CATEGORIA) REFERENCES CATEGORIA(CAT_ID),

    PUBLI_TIPO bool NOT NULL,
    PUBLI_NEGOCIABLE bool NOT NULL,
    PUBLI_VISIBLE bool NOT NULL,
    PUBLI_ACTIVA bool NOT NULL
);
